name: Deploy Waypoint ETL bundle
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/etl/**
      - .github/workflows/deploy-etl-bundle.yaml
env:
  DATABRICKS_AUTH_TYPE: oauth-m2m # OAuth seems to be the only type supported in free edition
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: apps/etl
    steps:
      - uses: actions/checkout@v6
      - uses: databricks/setup-cli@main
      - name: Validate bundle
        run: databricks bundle validate --strict
      - name: Deploy bundle
        run: databricks bundle deploy
